apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      httpMode: POST
      organization: pms
      defaultBucket: metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    isDefault: true
    version: 2
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 10s

  - name: ML Predictions
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      httpMode: POST
      organization: pms
      defaultBucket: predictions
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    version: 2
    editable: true

  - name: Alerts
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      httpMode: POST
      organization: pms
      defaultBucket: alerts
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    version: 2
    editable: true